export default {
    'tomato': require('./tomato.png'),
    'olive oil': require('./olive-oil.png'),
    'onion': require('./onion.png'),
    'spaghetti': require('./spaghetti.png'),
    'spices': require('./spices.png'),
    'sheets of gelatine': require('./sheets-of-gelatine.png'),
    'cheese': require('./cheese.png'),
    'white bread': require('./white-bread.png'),
    'ham': require('./ham.png'),
    'pineapple': require('./pineapple.png'),
    'butter': require('./butter.png'),
    'teaspoon melted butter': require('./butter.png'),
    'cattle hack': require('./cattle-hack.png'),
    'tomatoes': require('./tomatoes.png'),
    'cucumber': require('./cucumber.png'),
    'ketchup': require('./ketchup.png'),
    'burger buns': require('./burger-buns.png'),
    'veal cutlets': require('./veal-cutlets.png'),
    'eggs': require('./eggs.png'),
    'egg whites': require('./egg-whites.png'),
    'bread crumbs': require('./bread-crumbs.png'),
    'flour': require('./flour.png'),
    'vegetable oil': require('./vegetable-oil.png'),
    'salt': require('./salt.png'),
    'lemon slices': require('./lemon-slices.png'),
    'arugula': require('./arugula.png'),
    'lambs lettuce': require('./lambs-lettuce.png'),
    'parsley': require('./parsley.png'),
    'fennel': require('./fennel.png'),
    'smoked salmon': require('./smoked-salmon.png'),
    'mustard': require('./mustard.png'),
    'balsamic vinegar': require('./balsamic-vinegar.png'),
    'orange juice': require('./orange-juice.png'),
    'sugar': require('./sugar.png'),
    'yoghurt': require('./yoghurt.png'),
    'cream': require('./cream.png'),
    'orange peel': require('./orange-peel.png'),
    'baking powder': require('./baking-powder.png'),
    'white sugar': require('./white-sugar.png'),
    'milk': require('./milk.png'),
    'egg': require('./egg.png'),
    'chicken breasts': require('./chicken-breast.png'),
    'garlic': require('./garlic.png'),
    'ginger': require('./ginger.png'),
    'almond': require('./almond.png'),
    'cayenne pepper': require('./cayenne-pepper.png'),
    'pepper': require('./pepper.png'),
    'coconut milk': require('./coconut-milk.png'),
    'dark chocolate': require('./Dark-chocolate.png'),
    'cream of tartar': require('./cream-of-tartar.png'),
    'green asparagus': require('./green-asparagus.png'),
    'white asparagus': require('./white-asparagus.png'),
    'pine nuts': require('./pine-nuts.png'),
    'cherry tomatoes': require('./cherry-tomatoes.png'),
    'salad': require('./salad.png'),
}